name: "PHP Lint"

on: [push, pull_request]

# https://docs.github.com/en/actions/learn-github-actions/expressions
# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://github.com/actions/starter-workflows
# https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix


#on:
#  push:
#    paths-ignore:
#      - 'doc/**'
#  ...


permissions:
  contents: read

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.0"
          - "latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl"
          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"

      - name: "Lint PHP files"
        run: "find src/ test/ -type f -iname '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
